# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dreamreal',
            name='Din',
        ),
        migrations.AddField(
            model_name='dreamreal',
            name='din',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='dreamreal',
            name='dout',
            field=models.CharField(default='Null', max_length=50),
        ),
        migrations.AddField(
            model_name='dreamreal',
            name='dtot',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
