# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170414_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamreal',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
