# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170414_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamreal',
            name='date',
            field=models.DateField(),
        ),
    ]
