# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
